add --rule-models

diff --git a/ldv/ldv-task b/ldv/ldv-task
--- a/ldv/ldv-task
+++ b/ldv/ldv-task
@@ -30,7 +30,7 @@ fi;
 
 USER_WORKDIR=`echo $2 | sed 's/workdir=//'`
 if [ ! -d "$USER_WORKDIR" ]; then
-	echo "WARNING: User workdir not set or not exists: \"$1\". Try to use default ldv-tempdir: \"$TEMP_LDV_WORKDIR\".";
+	echo "ldv-task: WARNING: User workdir not set or not exists: \"$1\". Try to use default ldv-tempdir: \"$TEMP_LDV_WORKDIR\".";
 	if [ ! -d "$TEMP_LDV_WORKDIR" ]; then
 		mkdir $TEMP_LDV_WORKDIR;
 		if [ $? -ne 0 ]; then
@@ -80,6 +80,17 @@ for i in $@; do
 	# get KERNELDIR for this environment;
 	# kernel-manager return path if kernel-environment exists and correct prepared
 	ENV_ID=`echo $i | sed 's/:.*//'`;
+	rulemodels=`echo $i | sed 's/.*://'`;
+	echo "ldv-task: DEBUG: rulemodels: $rulemodels";
+	if [ ! -n "$rulemodels" ]; then
+		echo "ldv-task: ERROR: rulemodels after \":\" is null. Please, setup it.";
+		unset ENV_ID;
+		unset KERNEL_PATH;
+		unset WORK_DIR_LOCAL;
+		k=`expr $k + 1`;
+		tid=`expr $tid + 1`;
+		exit 1;
+	fi;
 	echo "ldv-task: INFO: env_id: $ENV_ID";
 	echo "ldv-task: INFO: workdir: $WORK_DIR_LOCAL";
 	KERNEL_PATH=`$LDV_KMANAGER getpath $ENV_ID`;
@@ -104,8 +115,8 @@ for i in $@; do
 	fi;
 
 
-	echo "WORK_DIR=$WORK_DIR_LOCAL $LDV_CORE_EXEC --basedir=$WORK_DIR_NEXT_INSTRUMENT --env=$KERNEL_PATH --driver=$DRIVER_ABS;"
-	WORK_DIR=$WORK_DIR_LOCAL $LDV_CORE_EXEC --basedir=$WORK_DIR_NEXT_INSTRUMENT --env=$KERNEL_PATH --driver=$DRIVER_ABS;
+	echo "WORK_DIR=$WORK_DIR_LOCAL $LDV_CORE_EXEC --basedir=$WORK_DIR_NEXT_INSTRUMENT --env=$KERNEL_PATH --driver=$DRIVER_ABS --rule-models=$rulemodels;"
+	WORK_DIR=$WORK_DIR_LOCAL $LDV_CORE_EXEC --basedir=$WORK_DIR_NEXT_INSTRUMENT --env=$KERNEL_PATH --driver=$DRIVER_ABS --rule-models=$rulemodels;
 	if [ $? -ne 0 ]; then
 		echo "ldv-task: ERROR: ldv-core failed.";
 	fi;
