add iter for kernels

diff --git a/ldv/ldv-task b/ldv/ldv-task
--- a/ldv/ldv-task
+++ b/ldv/ldv-task
@@ -13,7 +13,7 @@ LDV_KMANAGER=$LDV_DIR/ldv-kmanager;
 LDV_CORE_DIR=$LDV_HOME/ldv-core;
 LDV_CORE_EXEC=$LDV_CORE_DIR/ldv-core;
 
-DRIVER_ABS=`readlink -f $2`;
+DRIVER_ABS=`readlink -f $1`;
 if [ $? -ne 0 ]; then
 	echo "ldv-task: ERROR:  can't find abs-path for driver.";
 	exit 1;
@@ -52,20 +52,29 @@ if [ ! -d "$USER_WORKDIR" ]; then
 		exit 1;
 	fi;
 else
-	WORK_DIR=$USER_WORKDIR;
+	WORK_DIR=`readlink -f $USER_WORKDIR`;
 fi;
 echo "ldv-task: INFO: temp workdir: $WORK_DIR";
 # all temp dirs created... 
-k=2;
+k=1;
+tid=1;
 for i in $@; do
-	if [ -n "$USER_WORKDIR" -a $k -eq 2 ]; then let k=$k+1; continue; fi;
+	if [ $k -eq 1 ]; then
+		let k=$k+1;
+		continue;	
+	elif [ -n "$USER_WORKDIR" -a $k -eq 2 ]; then 
+		let k=$k+1; 
+		continue; 
+	fi;
+	echo -e "\nldv-task: $i";
 	# create dir for this stage
-	WORK_DIR_LOCAL=$WORK_DIR/$k;
+	WORK_DIR_LOCAL=$WORK_DIR/$tid;
 	mkdir $WORK_DIR_LOCAL;
 	if [ $? -ne 0 ]; then
 		echo "ldv-task: ERROR: can not create environment-dir from task: \"$WORK_DIR_LOCAL\".";
 		unset WORK_DIR_LOCAL;
 		let k=$k+1;
+		let tid=$tid+1;
 		exit 1;
 	fi;
 	# get KERNELDIR for this environment;
@@ -79,15 +88,19 @@ for i in $@; do
 		unset ENV_ID;
 		unset KERNEL_PATH;
 		unset WORK_DIR_LOCAL;
+		let tid=$tid+1;
 		let k=$k+1;
 		exit 1;
 	fi;
-	echo "Ok - next iterate";
-#	$LDV_CORE_EXEC $WORK_DIR_LOCAL $KERNEL_DIR $DRIVER
+	$LDV_CORE_EXEC $WORK_DIR_LOCAL $KERNEL_PATH $DRIVER_ABS;
+	if [ $? -ne 0 ]; then
+		echo "ldv-task: ERROR: ldv-core failed.";
+	fi;
 	unset ENV_ID;
 	unset KERNEL_PATH;
 	unset WORK_DIR_LOCAL;
 	let k=$k+1;
+	let tid=$tid+1;
 done;
 
 
